### ISSUE TITLE
Windows init.bat issues with install?

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/bpms-helpdesk-demo#11]
Fix needed here as in https://github.com/jbossdemocentral/bpms-rewards-demo/issues/10

**Comment by sabre1041** [comment]
EAP is referencing the jboss-eap-6.4.3-installer.jar on the 6.2 branch. Is this intended?

**Comment by eschabell** [comment]
Not yet updated this demo...

**Comment by eschabell** [comment]
Pushed updates to 6.2 branch, the process does not work so just test installer please.

**Comment by sabre1041** [comment]
Installer test passed successfully
